language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
notifications:
  slack:
    secure: rFQUTIgxa7TqiIvJyxBTNxiiFaPk4lsGPaMGaaVFC/vqLISx4JLMVeaChjRN+brtUaiFsRY+goNe+zFg0VJNVHTrTAO1lmI4yeRVYeXDadhwlhLRYRb2B/j7M6IgOeCr8MXi5t4JJDufHDbzHbhJreyDfpo3O65Tyz22d+MCVUz6HgwxIad20zK5fhFDey+vVPO3y6bqMzgeImgtEMZDe6nLqBWjKWvLjG0EWZjjNNpjNYBf0SMQbmE1Sw5pVmrAi2imD0L6l9Cuvq2U2Fw0ETS9JY6XZWz3A7Ah5XoSosE7ieJB3FA74qNvxH5dhY24oFxAsJUgVIHDqENJtvPiJiYZFLzSamEz9hHc5ciSp0LaTJ11y33n+Q4UIVvzl8S/eNIQqb5nAxVBPaFsyKMmmr8r2wcueDvkexOOZ4uZ20OizQjkt96TTNj4Z1A3q2jTkRpsEnuoQANGMKtT2QluYKckc7HAjSaDqR3sErFVg+hqPb4cpDzSiSwrQXfGlKFVGg8w+B5muds7cavMIA1xWX2jCnAZT2VcuavGXw5HJ3A4qwwpcAaPF8HDbp08stzThYmPJdBxzI5TPTK58Z1Dqy+dBU44DLpxe0tQkqiNCG7RMPjrCRkqTyHL7Ywj6OPb8OWc6exHP7ub1AeNjD3w0nyVrTDzIgwxGDkHdI/qy7I=
